if (!require("mvtnorm")) install.packages("mvtnorm")
if (!require("extraDistr")) install.packages("extraDistr")
if (!require("mvQuad")) install.packages("mvQuad")
if (!require("docstring")) install.packages("docstring")
if (!require("texmex")) install.packages("texmex")
if (!require("ExtremalDep")) install.packages("ExtremalDep")
if (!require("pracma")) install.packages("pracma")
if (!require("R.utils")) install.packages("R.utils")
if (!require("extremis")) install.packages("extremis")
if (!require("parallel")) install.packages("parallel")


library(mvtnorm)
library(extraDistr)
library(mvQuad)
library(docstring)
library(texmex)
library(ExtremalDep)
library(pracma)
library(R.utils)
library(extremis)
library(plyr)

source("truncated_bivariate_t_distribution.R")
source("prob_set_diff.R")
source("estimation_np.R")
source("Q_hat.R")
source("theta_hill.R")
source("constmle.R")
source("cv_h.R")
source("angdensity.default.R")
source("cens_bbeed_mar.R")
source("bbeed_thresh_mar.R")
